server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: service-a-user
          uri: http://localhost:8081
          predicates:
            - Path=/service-a/hello-user/**
          filters:
            - SetRequestHeader=X-API-KEY,access-key

        - id: service-a-admin
          uri: http://localhost:8081
          predicates:
            - Path=/service-a/hello-admin/**
          filters:
            - SetRequestHeader=X-API-KEY,access-key

        - id: service-b
          uri: http://localhost:8082
          predicates:
            - Path=/service-b/**
          filters:
            - SetRequestHeader=X-API-KEY,access-key
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/gateway-realm